In [2]:
import pandas as pd

In [8]:
# data=pd.read_csv(r"student.csv")

# print(data)


# in cmd ====> pip install pandas openpyxl
import openpyxl
data1=pd.read_excel(r"student.xlsx")

print(data1)

              timestamp  roll_num         name    middlename     surname  \
0   30/05/2023 14:26:35   2201184      Shubham        Kumar        Sinha
1   30/05/2023 14:26:56   2201129       Pranav      Prashant      Modale
2   30/05/2023 14:27:27   2201125      Pratik        Sharad     Masalkar
3   30/05/2023 14:27:43   2201154       Ranvir       Gajanan       Pawar
4   30/05/2023 14:27:48   2201193    Siddhesh         Suresh     Uttekar
5   30/05/2023 14:28:03   2201115       Sairaj       Shirish    Lumpatki
6   30/05/2023 14:28:03   2201110       Rahul          Kumar       Kumar
7   30/05/2023 14:28:06   2201124       Akash      Sambhaji      Markile
8   30/05/2023 14:28:07   2201145       harsh        subhash     patidar
9   30/05/2023 14:28:08   2201105        Omkar        Milind    Kulkarni
10  30/05/2023 14:28:10   2201171      Prajwal        Pramod     Shendge
11  30/05/2023 14:28:10   2201121       tejas    Uttareshwar        mane
12  30/05/2023 14:28:11   2201159      Vaibhav        Kailas        Raut
13  30/05/2023 14:28:13   2201173      Gaurav          Mohan      Shimpi
14  30/05/2023 14:28:15   2201182      sindura         singh     rathore
15  30/05/2023 14:28:15   2201130      Hitesh    Dnyaneshwar   Mohadikar
16  30/05/2023 14:28:16   2201163      Janhavi          Ajit  Sangaonkar
17  30/05/2023 14:28:20   2201195         Raj                      Verma
18  30/05/2023 14:28:25   2201187       Manish       Maruti         Teke
19  30/05/2023 14:28:26   1951022      muskan        shabbir      shipai
20  30/05/2023 14:28:28   2201164    Ashutosh       Ghansham      Saoji
21  30/05/2023 14:28:29   2201133        VIVEK      YESHAVNT        MORE
22  30/05/2023 14:28:32   2201175    Sharvari          Sunil      Shinde
23  30/05/2023 14:28:38   2201190       Leena         Sanjay      Thorat
24  30/05/2023 14:28:41   2201085      vedika   Gorakshanth     kandekar
25  30/05/2023 14:28:47   2201144     Atharva         Jayant    Paradkar
26  30/05/2023 14:28:48   2201196    himanshi                       vyas
27  30/05/2023 14:28:58    220126     Harshita                    Maurya
28  30/05/2023 14:28:59   2201146        Aditi     Pandurang       Patil
29  30/05/2023 14:29:04   2201188      Akshata         vijay      thakre
30  30/05/2023 14:29:03   2201141      Mahima         Lallan         Pal
31  30/05/2023 14:29:06   2201113    Aishwarya        Prasad    Lokhande
32  30/05/2023 14:29:12   2201155      Manali         Prayag      Petare
33  30/05/2023 14:29:16   2201116      Ankita         Tanaji      Madane
34  30/05/2023 14:29:17   2201152         Yash      Rajgonda       Patil
35  30/05/2023 14:29:26   2201139     Apeksha              D       Nimje
36  30/05/2023 14:29:34   2201206     Saurabh         Sanjay        Zute
37  30/05/2023 14:29:43   2201200      Kshitij        Kishor        Wani
38  30/05/2023 14:29:46   2201123     Sandesh        Sudhir      Manohar
39  30/05/2023 14:29:59   2201158        Suyog       Bapurao        Raut
40  30/05/2023 14:30:07   2201104      Prerna          Nitin      Kukade
41  30/05/2023 14:30:15    220143       sakshi       santosh     patidar
42  30/05/2023 14:30:17   2201205       Jyoti              .       Yadav
43  30/05/2023 14:30:20   2201117      NILESH        PRAKASH     MAHAJAN
44  30/05/2023 14:30:26   2201166       Pranav        Pravin     Sarkale
45  30/05/2023 14:30:32   2201167          Raj      Rajendra       kumar
46  30/05/2023 14:30:39   2201157       Nikhil         Ashok       Rande
47  30/05/2023 14:31:04   2201118  â€Ž Shubham    â€Ž Sanjay    â€Ž Mali
48  30/05/2023 14:31:14   2201194    shraddha     jaiprakash       varma
49  30/05/2023 14:31:18   2201106       Priya         Pradip    Kulkarni
50  30/05/2023 14:31:47   2201107      Swapnil         Suhas    Kulkarni

     age   sgpa  gender      favorite_sport  native_city  year_of_passing_10th
0   23.0   8.29    Male  Cricket , Football        Patna                  2014
1   25.0   7.80    Male             Cricket         Pune                  2014
2    NaN   8.31    Male           Badminton         Pune                  2017
3    NaN   8.00    Male               chess      buldana                  2014
4   21.0   8.40    Male             cricket         Pune                  2016
5   20.0   8.71    Male          volleyball   Ahmednagar                  2017
6   23.0   7.50    Male           Badminton       Ranchi                  2015
7    NaN   7.79    Male             Cricket        Latur                  2016
8   22.0   8.00    Male          volleyball       indore                  2016
9   22.0   9.81    Male    Sachin Tendulkar         Pune                  2018
10  21.0   7.90    Male             Cricket        Miraj                  2018
11   NaN   7.85    Male             Cricket     Baramati                  2016
12   NaN   7.00    Male        Table tennis         Beed                  2016
13  22.0   8.90    Male             cricket      Shahada                  2017
14  23.0   8.10  Female             cricket  muzzafarpur                  2017
15  22.0   8.25    Male             Cricket       Nagpur                  2017
16   NaN   8.75  Female           Badminton     Kolhapur                  2017
17  23.0   7.71    Male             Cricket   Jamshedpur                  2017
18  22.0   8.46    Male             Cricket         Pune                  2016
19  21.0   8.05  Female             cricket         pune                  2017
20  23.0   7.54    Male             Cricket        Akola                  2017
21  21.0   7.60    Male        Table Tennis     Kolhapur                  2017
22  22.0   7.82  Female             cricket        karad                  2016
23  22.0   7.89  Female           Badminton       Shirdi                  2017
24  22.0   8.89  Female                   -   Ahmednagar                  2017
25  23.0   7.64    Male            Football         Pune                  2016
26  22.0   8.80  Female             cricket       indore                  2017
27  21.0   8.61  Female           Vollyball         Pune                  2017
28  21.0   8.00  Female            Football   Ahmednagar                  2017
29   NaN  75.00  Female             cricket         pune                  2017
30  22.0   7.68  Female           badminton        patna                  2015
31  22.0   9.10  Female           badminton         pune                  2017
32  21.0   7.90  Female            Football       Sangli                  2017
33   NaN   7.00  Female             Cricket        karad                  2017
34  21.0   7.21    Male             Cricket     Kolhapur                  2017
35  21.0   8.00  Female          Basketball       Nagpur                  2017
36   NaN   7.50    Male             Cricket     Parbhani                  2016
37   NaN   7.60    Male             Cricket       Nagpur                  2015
38  22.0   7.54    Male            Football       Mumbai                  2016
39  22.0   7.67    Male             cricket         pune                  2017
40  21.0   7.40  Female           Badminton         Pune                  2017
41  22.0  10.00  Female             cricket         durg                  2015
42   NaN   8.14  Female             Cricket        Alwar                  2012
43  22.0   7.56    Male           BADMINTON      WADGAON                  2017
44  21.0   7.96    Male              Carrom         Pune                  2017
45  22.0   9.60    Male             cricket         pune                  2016
46   NaN   7.00    Male             Kabaddi         Akot                  2016
47  21.0   9.15    Male         â€Ž Cricket     â€Ž Pune                  2017
48  22.0   7.89  Female           badminton         wani                  2017
49  22.0   8.00  Female           Badminton         Pune                  2017
50  22.0   7.28    Male             Cricket         Pune                  2016